-- Policy notes for BodyPlan. Canonical SQL is supabase/migrations/0001_init.sql.
--
-- authenticated: owner_id = auth.uid()
-- anon: revoked on every personal table (including training_days)
-- DEFAULT_OWNER_ID is test/fixture only — do not bake it into RLS.
--
-- Optional when Auth is on in the project:
--   alter table public.profiles
--     add constraint profiles_owner_id_auth_fk
--     foreign key (owner_id) references auth.users (id);
--
-- Do not apply without credentials.
-- See docs/decisions/0004-auth-at-persistence.md.
