-- Policy notes for BodyPlan. Canonical SQL is supabase/migrations/0001_init.sql.
--
-- v1: owner_id = '198e5a49-c748-4bcc-b6ad-86445a76eb7b' (DEFAULT_OWNER_ID)
--     for both anon and authenticated.
--
-- Phase 4b: owner_id = auth.uid() for authenticated; revoke anon.
--           Remap rows first (docs/decisions/0002-auth-ready-static.md).
--
-- Do not apply without credentials.
