#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE="${ENV_FILE:-.env.local}"
DASHBOARD="https://supabase.com/dashboard"
CONNECT="https://supabase.com/dashboard/project/_?showConnect=true"
API_KEYS="https://supabase.com/dashboard/project/_/settings/api-keys"
AUTH_PROVIDERS="https://supabase.com/dashboard/project/_/auth/providers"
URL_CONFIG="https://supabase.com/dashboard/project/_/auth/url-configuration"
SQL_NEW="https://supabase.com/dashboard/project/_/sql/new"
PAGES_URL="https://nfernie.github.io/Katies-Adventures-2_Chapter-2"
LOCK_PROD="$PAGES_URL/lock/"
LOCK_LOCAL="http://localhost:3000/Katies-Adventures-2_Chapter-2/lock/"
REPO_VARS="https://github.com/NFernie/Katies-Adventures-2_Chapter-2/settings/variables/actions"

banner "Create a Supabase project for BodyPlan (one-time)"

stage "Create the project"
say "There is no project in this repo’s env. You create it in the dashboard."
say "The Pages app only needs the public URL + anon/publishable key."
open_url "$DASHBOARD"
step "Sign in (GitHub is fine)."
step "Click New project (org home, top right)."
step "Name: BodyPlan (or similar). Pick a region close to you."
step "Database password: Generate a password and store it in your password manager."
step "You will not put that password, or service_role, in the website."
step "Click Create new project. Wait until the project is Active (about a minute)."
pause "Press Enter when the project home has loaded."

stage "Copy Project URL and anon / publishable key"
say "The anon (legacy) or publishable key is public by design. Never copy service_role"
say "or a secret key (sb_secret_…)."
open_url "$CONNECT"
step "Top bar: Connect. Copy Project URL (https://<ref>.supabase.co)."
ask NEXT_PUBLIC_SUPABASE_URL "Paste the Project URL:"
open_url "$API_KEYS"
step "Left sidebar gear → Settings → API Keys (or the API Keys tab)."
step "Preferred: Publishable key (starts sb_publishable_)."
step "Or Legacy API Keys → anon public JWT. Same role: browser + RLS."
step "Do not copy service_role. Do not copy Secret keys."
ask_secret NEXT_PUBLIC_SUPABASE_ANON_KEY "Paste the anon or publishable key:"
if [[ "$NEXT_PUBLIC_SUPABASE_ANON_KEY" == *service_role* || "$NEXT_PUBLIC_SUPABASE_ANON_KEY" == sb_secret_* ]]; then
  warn "That looks like a secret/service_role key. Stop. Copy the anon/publishable key instead."
  exit 1
fi
write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"
set_var NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
set_var NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"
set_secret NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
set_secret NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"
pause "Press Enter after the values are saved locally."

stage "Enable Email — confirmation link on create, password on sign-in"
open_url "$AUTH_PROVIDERS"
step "Left sidebar: Authentication → Sign In / Providers."
step "Open Email."
step "Enable Email provider: ON (often already on)."
step "Leave Confirm email ON. Create account emails a confirmation link. Sign in uses password after that click."
step "Do not enable Google, Apple, GitHub, Phone, or Anonymous."
step "BodyPlan: Create account = one confirmation link. Sign in = confirmed email + password."
pause "Press Enter when Email is on and other providers are off."

stage "Site URL and redirect allow-list"
say "If /lock is missing from this list, the email link lands with no session."
say "Hosted Data API allows browser CORS by default — there is no extra CORS toggle."
say "If you later restrict CORS, allow $PAGES_URL and http://localhost:3000."
open_url "$URL_CONFIG"
step "Authentication → URL Configuration."
step "Site URL: $PAGES_URL   (no trailing slash required; do not use localhost as Site URL)."
step "Redirect URLs → Add URL, one per line, then Save:"
step "  $LOCK_PROD"
step "  $LOCK_LOCAL"
note "Optional extra: ${PAGES_URL}/** and http://localhost:3000/** if the UI wants a glob."
pause "Press Enter after Save."

stage "Apply auth-scoped SQL (no open v1 owner policy)"
say "Paste the repo files. Do not type an is_v1_owner policy. Do not grant anon."
open_url "$SQL_NEW"
step "Left sidebar: SQL Editor → New query."
step "New empty project: paste supabase/migrations/0001_init.sql, Run."
step "If tables already exist (0001 errors, gym_days_per_week still on profiles, or no training_days): paste 0003_repair_auth_rls.sql instead. Do not re-run 0001."
step "Then paste supabase/migrations/0004_day_plans_training_setting.sql and Run. Generate needs day_plans.training_setting."
step "You should see profiles without gym_days_per_week, plus training_days."
step "New query → optionally paste supabase/migrations/0002_owner_auth_fk.sql → Run."
step "0002 is optional (owner_id → auth.users). Skip it if Auth FKs error."
step "Table Editor → profiles → RLS should show ON. Policies: *_auth_owner using owner_id = auth.uid()."
step "From the repo: bash scripts/prove-supabase-anon.sh  (training_days exists; anon insert denied)."
pause "Press Enter after the repair SQL succeeds and the prove script is green."

stage "GitHub Actions secrets and variables for the Pages build"
say "NEXT_PUBLIC_ values are baked into the static export at build time."
say "The plan asked for Actions secrets; variables also work (the anon key is public)."
open_url "$REPO_VARS"
step "If set_secret / set_var above already wrote them, confirm they appear here."
step "Otherwise: Settings → Secrets and variables → Actions."
step "Secrets tab: NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY"
step "Variables tab: the same two names (optional duplicate; Pages reads secrets first)."
step "Do not add service_role, DATABASE_URL, or USDA_FDC_API_KEY as NEXT_PUBLIC_."
pause "Press Enter when both variables exist."

stage "Local smoke check"
say "Do not claim production until Create account confirms and Sign in works without a new email."
step "npm run dev → open $LOCK_LOCAL (You also has Sign in / Create account)."
step "Create account: email + password. Open the confirmation link on this device."
step "Sign out, then Sign in with the same email and password — no new email."
step "On You, save height/weight + at least one train day. Hard-refresh. Data stays."
step "Incognito window: same Pages URL. Personal rows stay hidden. No session."
note "Written walkthrough: docs/wizard/supabase-pages.md"
pause "Press Enter to finish. Live apply is yours; the agent cannot use your dashboard."

finish
note "Never put service_role in .env.local or GitHub variables."
